### ISSUE TITLE
Design QA

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/wildcoast#45]

**Comment by stutts** [comment]
Desktop QA - Stutts

- [ ]  UI - Looks like the white type over the maroon buttons renders super light. I think we should bump up a weight to remedy.
![image](https://user-images.githubusercontent.com/14879336/37434410-b574d71e-279c-11e8-86da-13d234366381.png)

- [ ]  UI - We can talk further about this if need be but I think we should just go ahead and switch all semi transparent white buttons to full white with the maroon text (so the hover state haha). I see legibility issues arising with the use of certain background photos (like the screenshot). Also for anyone that is slightly visually impaired this could also be an issue as is.
![image](https://user-images.githubusercontent.com/14879336/37434690-ab1ecdfa-279d-11e8-87c8-69aceb16456a.png)

- [ ]  FOOTER - Let's switch the typeface for "Resources" and "Blog" from Proxima Nova Extra Condensed to the typeface (and size) we're using for buttons (Lato).
![image](https://user-images.githubusercontent.com/14879336/37435120-5719fde0-279f-11e8-85bf-10b32cbf8673.png)

- [ ]  ABOUT US - If you guys have the time, I'd like for the plus signs of the FAQs section to be centered vertically and for the padding on the right of them to equal or be close to the left padding of the text in each FAQ.
![image](https://user-images.githubusercontent.com/14879336/37435479-bf4d73fa-27a0-11e8-85b2-2d035653768e.png)

- [ ]  CORAL REEFS - Let's darken the lightest overlay on the Our Impact section so there's a little more contrast between the white text and the lighter parts of the background photo.
![image](https://user-images.githubusercontent.com/14879336/37436034-40d959aa-27a3-11e8-890e-b5d787791062.png)

- [ ]  JOIN US - This may be a universal style that is used in multiple places but if it could be lightened a tad I think it would help this Partnerships section.
![image](https://user-images.githubusercontent.com/14879336/37436183-d5dea9ba-27a3-11e8-8281-d82b6ecbfeeb.png)


I know this one wasn't the easiest project as a whole but you guys did a really great job of pulling it all together. Bravo.

**Comment by wstecklair** [comment]
**Mobile Design QA**

Overall looks great! You were right, almost looks better on mobile than on desktop. As usual, you did a great job on the build, hardly anything needs attention :) Love working with you!

Here's my feedback...

**Home**
- [ ] Can we pad the top and bottom of the white Who We Are section...

![img_e555bc810896-1](https://user-images.githubusercontent.com/28412045/37485789-abe00ba8-2849-11e8-8ce1-2fde17ee25e3.jpeg)


- [ ] The rotating thumbs promo section is a little weird on mobile, it's tough to tell you can swipe to rotate when you get to the section because the indicator dots are off screen. Then when you see them and swipe, you're too far down and have a cutoff thumbnail image. Perhaps change the photo to the same width, but more of a 16:9 ratio so you get it all in view at once. Does that make sense?

![img_0753](https://user-images.githubusercontent.com/28412045/37485965-4b135874-284a-11e8-82a8-278c604ef3e9.PNG)
![img_0754](https://user-images.githubusercontent.com/28412045/37485966-4b2e9274-284a-11e8-9f41-f966b3c213c8.PNG)


**About Us**
- [ ] Increase the top/bottom padding in the first white section (same as the Who We Are section on the homepage)

**What We Do**
- [ ] Increase the top/bottom padding in the first white section (same as the Who We Are section on the homepage)
- [ ] Rotating promo thumbs (same as on homepage)

**Coral Reefs**
- [ ] The map section is kinda trippy. Scrolling past it is really tricky. Almost impossible. Let's talk so I can show you.

- [ ] More of Our Work rotator at the bottom of the page could use a bit of shortening the height. Same feelings/issues as the rotating promo thumbs.

**Where We Work**
- [ ] The map is tricky to use, might need adjusting (perhaps you (of Jaq) is still working on it)

**Events**
- [ ] Page is blank. Assuming this will populate upon launch.
